coverage:
  status:
    # Ensure each PR hits at least 80% coverage
    patch:
      default:
        target: 80%

    # Allow some leniency when coverage is high
    project:
      default:
        target: auto
        threshold: 5%
